version: '3'
services:
  jupyter:
    build: .
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
    volumes:
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
  indi-server:
    build: .
    command: indiserver -v indi_simulator_ccd indi_simulator_telescope indi_simulator_gps
    ports:
      - "7624:7624"
